### ISSUE TITLE
How to run a single linearizability test?

### ISSUE THREAD

**Issue by you-n-g** [Kotlin/kotlinx-lincheck#106]
Thanks for your previous [kind reply](https://github.com/Kotlin/kotlinx-lincheck/issues/105), I've successfully run `./gradlew build`  

Now I want to run the test ConcurrentLinkedQueueTest.

I've tried the following commands. However, all of them failed
```shell
./gradlew test  --tests org.jetbrains.kotlinx.lincheck.test.verifier.linearizability.ConcurrentLinkedQueueTest -i
./gradlew test  -Dtest.single=org.jetbrains.kotlinx.lincheck.test.verifier.linearizability.ConcurrentLinkedQueueTest
gradle test --tests org.jetbrains.kotlinx.lincheck.test.verifier.linearizability.ConcurrentLinkedQueueTest -i
gradle test --tests ConcurrentLinkedQueueTest -i

cd build/classes/kotlin/jvm/test/
java -cp .  org.jetbrains.kotlinx.lincheck.test.verifier.linearizability.ConcurrentLinkedQueueTest
java -cp .:$PROJ_PATH/kotlinx-lincheck/build/libs/lincheck-jvm-2.14.1.jar  org.jetbrains.kotlinx.lincheck.test.verifier.linearizability.ConcurrentLinkedQueueTest
```

Could you give me any hint that how to run a single test?
Thanks

**Comment by you-n-g** [comment]
And then, I installed `kotlinc` and tried following command.
`ConcurrentQueueTest.kt`'s content is same as https://github.com/Kotlin/kotlinx-lincheck#test-example
```
kotlinc -cp ../build/libs/lincheck-jvm-2.14.1.jar  ConcurrentQueueTest.kt
```

However, it doesn't work.

**Comment by ndkoval** [comment]
Please use the `jvmTest` task for this purpose, e.g.
```
./gradlew jvmTest --tests HashMapTest
```

**Comment by you-n-g** [comment]
@ndkoval 
Thanks so much for your reply.

**Comment by you-n-g** [comment]
@ndkoval 
I follow your guidance and run the examples successfully.
May I ask how to get output like this example? 
https://github.com/Kotlin/kotlinx-lincheck#example 

Thanks!

**Comment by alefedor** [comment]
@you-n-g 
Our internal tests are to test lincheck, not the data structures, so _expected_ failures are just suppressed.
If you run lincheck via 
```
LinChecker.check(HashMapLinearizabilityTest.class);
```
as in the example, you'll get the output

**Comment by you-n-g** [comment]
@alefedor  Thanks so much!
