### ISSUE TITLE
How to check the time cost of a test

### ISSUE THREAD

**Issue by you-n-g** [Kotlin/kotlinx-lincheck#107]
Hi, 
Thanks to your help, I've successfully built and run [the example](https://github.com/Kotlin/kotlinx-lincheck#example)

I have one more question now.
How could I get the time cost of a Linearizability Test?

For example, each run of a Linearizability verification test consists of the following time.
- the starting of the program 
- time of collecting the trace.
- time of linearizability verification
- post-processing( I'm not sure if there is this step)

I want to get the time cost of linearizability verification.

Thanks :)

**Comment by you-n-g** [comment]
I go through the docs but didn't find any related docs.
Now I plan to use some profiling tools to get the detailed timing.

**Comment by you-n-g** [comment]
Finally, I find a profiling tool named [async-profiler](https://github.com/jvm-profiling-tools/async-profiler)

The test cost 6171 samples and  15.801 seconds
![image](https://user-images.githubusercontent.com/465606/126527433-3f65b4a4-f04d-4a55-8635-d4a0f3557f83.png)



About 1380 samples are in  `org/jetbrains/kotlinx/lincheck/LinChecker.run` (`val failure = scenario.run(this, verifier)`)  
![image](https://user-images.githubusercontent.com/465606/126527867-c00a0f81-1e02-46bb-848b-560f8b8bb1b1.png)

So I think the time of linearizability verification is about  1380/6171  * 15.801 =  3.5335 seconds

The timing solution is very cumbersome. I will appreciate you if you have any more convenient solution.

Thanks.

**Comment by alefedor** [comment]
@you-n-g
Do you mean by `linearizability verification` linearizability verification of _execution results_?
In this case you may be interested in [`Verifier.verifyResults`](https://github.com/Kotlin/kotlinx-lincheck/blob/064e8112fde4fbf47c9d72cd8e88e8debab464be/src/jvm/main/org/jetbrains/kotlinx/lincheck/verifier/Verifier.java#L41) method.

By the way:
* There are no separate trace collection and verification phases. After every invocation the execution results are verified.
* Your way of estimating times apparently shows not what you want. There are several threads and the main one spends _almost all_ the time in `LinChecker.run` method. Other samples are collected from parallel threads.

**Comment by you-n-g** [comment]
@alefedor  
Thanks for your reply
I'm interested in the time information of the verification process.  Can  `Verifier.verifyResults` provide this information?
Besides, I don't understand how to access the  `Verifier.verifyResults`.    The `check` function returns void.
![image](https://user-images.githubusercontent.com/465606/126583739-e8859482-1790-478b-a31c-947995dbc6fd.png)


> Your way of estimating times apparently shows not what you want. There are several threads and the main one spends almost all the time in LinChecker.run method. Other samples are collected from parallel threads.
Is it correct that my way of estimating time includes both trace collection and verification of multiple threads? 

Thanks

P.S.
Attached is the profiling file I got from async-profiler. 
[profile.zip](https://github.com/Kotlin/kotlinx-lincheck/files/6859750/profile.zip)

**Comment by alefedor** [comment]
@you-n-g 
> Can Verifier.verifyResults provide this information?

No, but this is the method you want to time.

**Comment by you-n-g** [comment]
@alefedor 
Thanks so much!

So is it correct that the time for verification in my case is about   276 / 6171 * 15.801 = 0.70670? 

![image](https://user-images.githubusercontent.com/465606/126587022-a8d6f6b1-8f70-4775-927e-8657b31d9ea4.png)

**Comment by alefedor** [comment]
@you-n-g 
There is still problem with parallel threads in your estimations.
More realistic will be `Verifier.verify` samples / `Lincheck.check` samples * Time = 276 / 1400 * 15.8 = 3.11
Yet, I'm not sure whether async profiler works as expected in case of blocking methods such as `Thread.join`.

Besides, I can not understand what you are trying to estimate.
If it is the `percentage of time spent on verification`, it depends on number of iterations/invocations, size of test scenarios and the tested data structure.

**Comment by you-n-g** [comment]
Thanks so much for such detailed advice :) 

My motivation is to measure the  time cost of linearization verification given a specific example under different settings (iterations, actorsPerThread, threads)
