### ISSUE TITLE
Instruction in readme outdated with respect to package hosting

### ISSUE THREAD

**Issue by danwt** [Kotlin/kotlinx-lincheck#112]
Bintray and JCenter have been deprecated and the readme has not been updated to reflect it.

**Comment by LouisCAD** [comment]
@alefedor Should we send a PR?

**Comment by alefedor** [comment]
@LouisCAD I don't think it's needed. We will fix this minor issue in the PR that also fixes other Bintray dependencies

**Comment by LouisCAD** [comment]
Is that PR #113?

**Comment by ndkoval** [comment]
@LouisCAD you are right, we will fix the link in #113. I will close the issue then.
