### ISSUE TITLE
unit test implementation for repository

### ISSUE THREAD

**Issue by marcela-cardona-s** [Kotlin/kotlinx-lincheck#129]
Hi, I have an implementation question for a unit test.

How can I test this case, where I need to mock the repository because I'm not interested in actually saving it, but I'm interested in knowing what the concurrency behavior is when saving information.

**Code:**
<img width="324" alt="image" src="https://user-images.githubusercontent.com/104914336/202549970-9d0f1098-7a21-4357-9d16-d9c12a03c506.png">

**Test:**
<img width="484" alt="image" src="https://user-images.githubusercontent.com/104914336/202550011-7f0d09ef-ac37-4a53-8d59-56e8d99034a4.png">

**Repository:**
<img width="369" alt="image" src="https://user-images.githubusercontent.com/104914336/202550322-4837b226-8b7d-401d-ac3b-fb111840ab37.png">

**Entity:**
<img width="478" alt="image" src="https://user-images.githubusercontent.com/104914336/202550206-433532db-8965-41fc-b6d2-a81ecadca5d5.png">

**Comment by ndkoval** [comment]
Hi @marcela-cardona-s ,

It is unclear what behaviour you want to test and which contract should be ensured. Could you clarify, please?

**Comment by marcela-cardona-s** [comment]
I am trying to test the behavior of the `launch` coroutine that guarantees that there are no concurrency problems when saving to any database (repository), the idea is to be able to mock this component and when executing this test the injection does not work of dependencies given by @Mockk. What I hope is to be able to verify that there will be no concurrency problems when storing the information.
