### ISSUE TITLE
Thread yield transformer implementation is slightly incorrect

### ISSUE THREAD

**Issue by kkarnauk** [Kotlin/kotlinx-lincheck#132]
Version: 2.16 (and the previous ones, too)

**Issue**

As you can see in the implementation of [ThreadYieldTransformer](https://github.com/Kotlin/kotlinx-lincheck/blob/e27dff8ed99824be1c6da626ccafc4893c3d77bf/src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategyTransformer.kt#L695), in order to understand whether it should remove `yield`-call, it checkes `owner`. But it doesn't take into account that `owner` means the actual callee (not the concrete class which method will be called).

In Java it's possible to call static methods from base classes. So, if we have a derived thread instance and call its `yield`, then it will not be removed. 

But, I'm not sure that it's a big problem, because I think that almost all users call exactly `Thread.yield()`. 

**How to fix**

We can easily check that `owner` extends `Thread` as it's done in [RandomTransformer](https://github.com/Kotlin/kotlinx-lincheck/blob/e27dff8ed99824be1c6da626ccafc4893c3d77bf/src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategyTransformer.kt#L684). ASAIU, it fixes the problem.

**Comment by ndkoval** [comment]
We will get rid of this optimization and remove [ThreadYieldTransformer](https://github.com/Kotlin/kotlinx-lincheck/blob/e27dff8ed99824be1c6da626ccafc4893c3d77bf/src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategyTransformer.kt#L695), it does not really help in practice.
