### ISSUE TITLE
Deprecate`logLevel` and introduce an internal `lincheck.debug` system property instead

### ISSUE THREAD

**Issue by ndkoval** [Kotlin/kotlinx-lincheck#157]
The `logLevel` property is used internally when debugging Lincheck. It should be separate from the API and is rarely needed, even when developing Lincheck itself. Let's deprecate the `logLevel` property and introduce the `lincheck.debug` system property instead. Thus, to print the debug info, one needs to run the process with `-Dlincheck.debug=true`. This will be an internal property for internal use.

**Comment by eupp** [comment]
Also, maybe we can just use some existing logging library, like [kotlin-logging](https://github.com/oshai/kotlin-logging)?

**Comment by ndkoval** [comment]
We don't need such a library, as this property should enable the debug output for us, the developers.

**Comment by ndkoval** [comment]
There is a better option: we will keep it as a part of the _internal_ API. Therefore, I'm closing the issue.
