### ISSUE TITLE
Gradle/maven instructions

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx-lincheck#21]
Gradle/Maven setup instructions are missing. It's not that easy to get where is `jagent-impl` and how to include it.

So it should be a snippet somewhere like this:

```gradle
maven { url 'https://kotlin.bintray.com/kotlinx' }
maven { url 'https://dl.bintray.com/devexperts/Maven' }
```

**Comment by ndkoval** [comment]
We removed this dependency in #30, no need to add Devexperts Bintray repository anymore.
