### ISSUE TITLE
Null values handled incorrectly

### ISSUE THREAD

**Issue by ark-1** [Kotlin/kotlinx-lincheck#78]
It should be `Serializable?`, right?

https://github.com/Kotlin/kotlinx-lincheck/blob/fda4d46a72b71af8e127ede7ab9429d135829eaf/src/jvm/main/org/jetbrains/kotlinx/lincheck/Result.kt#L50

**Comment by Krock21rus** [comment]
https://github.com/Kotlin/kotlinx-lincheck/tree/fda4d46a72b71af8e127ede7ab9429d135829eaf#parameter-and-result-types

**Comment by ark-1** [comment]
The class I used is `Serializable`, but the type is nullable. Is there a reason, why null values should be prohibited there? It can be serialized as easily as other values.

**Comment by alefedor** [comment]
@ark-1 
You are right, this is a bug, although not easy to reproduce. Will be fixed in the next release.
