### ISSUE TITLE
[PROPOSAL] Binding of tested operations to data

### ISSUE THREAD

**Issue by sh-ad** [Kotlin/kotlinx-lincheck#86]
When testing concurrent data structures, it seems useful to provide information to Linkchek about conjugate operations. Conjugate operations are operations that must be performed on the same data in order to be interesting in terms of how the data structure works. For example, for Set, add and delete operations will be conjugate.

Linkchek now needs to do a lot of unnecessary iterations to find useful cases. Any conjugate operations with different operands are the same option. Only the order of execution of operations will differ.

Now:
```
Execution scenario (init part):
[add(6), remove(1), remove(4), isEmpty(), add(0)]
Execution scenario (parallel part):
| remove(-10) | remove(10)  | remove(4)  | isEmpty() |
| add(-9)     | isEmpty()   | add(-7)    | remove(7) |
| remove(1)   | remove(-8)  | remove(6)  | remove(-4)|
```
Proposal:
```
Execution scenario (init part):
[add(6), remove(1), remove(4), isEmpty(), add(0)]
Execution scenario (parallel part):
| add(-10)   | remove(-10)| remove(4)| isEmpty() |
| add(4)     | isEmpty()  | add(8)   | add(1)    |
| remove(-2) | remove(-8) | remove(6)| remove(-4)|
```

A similar result is given by narrowing the range of generated values ​​for the operands:
```
Execution scenario (init part):
[add(1), isEmpty(), isEmpty(), remove(2), remove(2)]
Execution scenario (parallel part):
| remove(3) | remove(3) | add(3)    | add(3)    |
| remove(1) | remove(1) | remove(3) | remove(3) |
| isEmpty() | remove(3) | remove(3) | isEmpty() |
```
However, this method is not suitable for some data structures, for example, Hashmap, so it is important to add the ability to specify conjugate operations.

**Comment by ndkoval** [comment]
Hi @sh-ad,

Could you please suggest an API on how conjugate operations should be specified? That would be extremely helpful!
