### ISSUE TITLE
[PROPOSAL] Binding a method to a  separate thread

### ISSUE THREAD

**Issue by sh-ad** [Kotlin/kotlinx-lincheck#87]
Scanning operations are common in concurrent data structures. Scanning operations are operations that, in the course of their execution, go through all the elements. For example, for a Set, this would be "isEpmty".
For testing, the most interesting option seems to be when such operations will be performed in a separate thread. This will increase the number of cases when several operations are performed on one element at once.

Now:
```
Execution scenario (init part):
[add(6), remove(1), remove(4), isEmpty(), add(0)]
Execution scenario (parallel part):
| remove(-10) | isEmpty()   | remove(4)  | isEmpty() |
| add(-9)     | isEmpty()   | add(-7)    | remove(7) |
| isEmpty()   | remove(-8)  | remove(6)  | isEmpty()|
```

Proposal:
```
Execution scenario (init part):
[add(6), remove(1), remove(4), isEmpty(), add(0)]
Execution scenario (parallel part):
| isEmpty() | remove(-10)| remove(4)| add(8)    |
| isEmpty() | isEmpty()  | add(8)   | add(1)    |
| isEmpty() | remove(-8) | remove(6)| remove(-4)|
```

**Comment by alefedor** [comment]
@sh-ad  
Hi!
Technically, you can write your own `ScenarioGenerator`, but I agree that it is not an easy and enjoyable code.
Instead of just binding a thread we probably want a more general scenario specification.
Do you have any ideas on how the scenario should be configured?
For example, we can try to add a type-safe builder for Kotlin that looks like
```
options.scenario {
  thread {
    actorsPerThread(3)
    operations(TestSet::isEmpty)
  }
  repeat(3) { 
    thread() // just a default thread
  }
}
```

**Comment by sh-ad** [comment]
@alefedor 
Thank you, I wrote my own generator that solves the problem.

Did I get the idea right, to make it possible to configure each individual thread through the builder?

**Comment by alefedor** [comment]
@sh-ad 
Yes, you are right. The idea is to choose the types and the number of operations in each thread

**Comment by sh-ad** [comment]
@alefedor
I will try to implement this idea.

Is the implementation details better discussed here or elsewhere?

**Comment by alefedor** [comment]
@sh-ad 
That's great that you want to implement this. Thank you!
> Is the implementation details better discussed here or elsewhere?

How about telegram?
Telegram: @Alehard

**Comment by sh-ad** [comment]
Summary:
- It seems interesting to add functionality that would allow you to configure scenario generation in more detail, right down to the level of operations.
- Create a separate issue with a description of this
- Collect usage cases there

https://github.com/Kotlin/kotlinx-lincheck/issues/90
