### ISSUE TITLE
Scenario minimization causes java.lang.OutOfMemoryError 

### ISSUE THREAD

**Issue by mvicsokolova** [Kotlin/kotlinx-lincheck#91]
Scenario minimization results in `java.lang.OutOfMemoryError` because of multiple recursive invocations.

[Here is the test](https://github.com/Kotlin/kotlinx-lincheck/blob/1cf7dfb002ea3f47ec1c8c295658a28378116b26/src/jvm/test/org/jetbrains/kotlinx/lincheck/test/strategy/modelchecking/MultiMapTest.kt) to reproduce the error: 
`runModelCheckingTest()` fails  with `java.lang.OutOfMemoryError: Java heap space` if `minimizeFailedScenario` is true.

**Comment by alefedor** [comment]
@mvicsokolova 

Hi!
You are right. There is a memory leak due to recursion
