### ISSUE TITLE
Modular testing: adding guarantees on methods of java.util.concurrent.* classes fails

### ISSUE THREAD

**Issue by mvicsokolova** [Kotlin/kotlinx-lincheck#92]
I'm trying to add atomic guarantees for all methods of `java.util.concurrent.ConcurrentHashMap` like this:

```
@Test
    fun runModularTesting() = ModelCheckingOptions()
        ...
        .addGuarantee(forClasses("java.util.concurrent.ConcurrentHashMap").allMethods().treatAsAtomic())
        .check(this::class.java)
```

The test fails with the following error: 
```
java.lang.IllegalStateException: The result should either be a type always loaded by the system class loader (e.g., Int, String, List<T>) or implement Serializable interface; the actual class is null.
```

[Here is the test](https://github.com/Kotlin/kotlinx-lincheck/blob/1cf7dfb002ea3f47ec1c8c295658a28378116b26/src/jvm/test/org/jetbrains/kotlinx/lincheck/test/strategy/modelchecking/MultiMapTest.kt) to reproduce the error (`runModularTesting `).

**Comment by alefedor** [comment]
@mvicsokolova

Hi!
The error you mention is not connected to atomic guarantees and there already is a [fix](https://github.com/Kotlin/kotlinx-lincheck/pull/83) for it. I hope @ndkoval will eventually approve and merge it to _develop_.

However, there is another problem that causes `the execution has hung` error.
Luckily, this problem has a [fix](https://github.com/Kotlin/kotlinx-lincheck/pull/82) too.

**Comment by mvicsokolova** [comment]
Hi! 
Sounds great 🙏 Thank you!

**Comment by ndkoval** [comment]
@alefedor Are you sure? Surprisingly, changing
```
        .addGuarantee(forClasses("java.util.concurrent.ConcurrentHashMap").allMethods().treatAsAtomic())

```
to
```
        .addGuarantee(forClasses("org.jetbrains.kotlinx.lincheck.tran$f*rmed.java.util.concurrent.ConcurrentHashMap").allMethods().treatAsAtomic())
```
fixes the problem

**Comment by alefedor** [comment]
@ndkoval 
After changing one line to another I get the same error for modular testing and model checking test.
This disables guarantees and conceals a bug with `synchronized` in ignored sections.

**Comment by ndkoval** [comment]
@mvicsokolova does the recent 2.13 release solve your problem?

**Comment by mvicsokolova** [comment]
Yes, now it works. Thank you
