### ISSUE TITLE
Incorrect warning about state equivalency relation

### ISSUE THREAD

**Issue by mvicsokolova** [Kotlin/kotlinx-lincheck#96]
For tests in model checking mode, with scenario minimization turned on I get the warning about setting state equivalency repeated for every iteration of scenario minimization, I guess (with scenario minimization turned off it's ok).

Also there are several tips in the message itself, marked them in bold: 

_To verify outcome results faster, it is highly recommended to specify the state equivalence relation on **yoursequential** specification. However, on class org.jetbrains.kotlinx.lincheck.test.guide.LongAdderTest **it is is** not defined or is implemented incorrectly. Please, specify the equivalence relation via implementing `equals()` and `hashCode()` functions on class org.jetbrains.kotlinx.lincheck.test.guide.LongAdderTest. The most convenient way is to extend a special `VerifierState` class and override the `extractState()` function, **whichextracts** and returns the logical state, which is used for further `equals()` and `hashCode()` calls._

**Comment by ndkoval** [comment]
Already been fixed, but I forgot to mention the issue. Thanks for finding the mistakes!
